package com.leo.skelstub.HelloApp;


/**
* com/leo/skelstub/HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* martes, 24 de abril de 2018, 11:20:29 a. m. hora de verano de Europa central
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
