package com.leo.skelstub.HelloApp;


/**
* com/leo/skelstubTIE/HelloApp/HelloPOATie.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* martes, 24 de abril de 2018, 2:37:34 p. m. hora de verano de Europa central
*/

public class HelloPOATie extends HelloPOA
{

  // Constructors

  public HelloPOATie ( com.leo.skelstub.HelloApp.HelloOperations delegate ) {
      this._impl = delegate;
  }
  public HelloPOATie ( com.leo.skelstub.HelloApp.HelloOperations delegate , org.omg.PortableServer.POA poa ) {
      this._impl = delegate;
      this._poa      = poa;
  }
  public com.leo.skelstub.HelloApp.HelloOperations _delegate() {
      return this._impl;
  }
  public void _delegate (com.leo.skelstub.HelloApp.HelloOperations delegate ) {
      this._impl = delegate;
  }
  public org.omg.PortableServer.POA _default_POA() {
      if(_poa != null) {
          return _poa;
      }
      else {
          return super._default_POA();
      }
  }
  public String sayHello ()
  {
    return _impl.sayHello();
  } // sayHello

  public void shutdown ()
  {
    _impl.shutdown();
  } // shutdown

  private com.leo.skelstub.HelloApp.HelloOperations _impl;
  private org.omg.PortableServer.POA _poa;

} // class HelloPOATie
