package com.leo.skelstub.HelloApp;


/**
* com/leo/skelstub/HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* martes, 24 de abril de 2018, 11:20:29 a. m. hora de verano de Europa central
*/

public interface Hello extends HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Hello
