package com.leo.skelstub.HelloApp;

/**
* com/leo/skelstub/HelloApp/HelloHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* martes, 24 de abril de 2018, 11:20:29 a. m. hora de verano de Europa central
*/

public final class HelloHolder implements org.omg.CORBA.portable.Streamable
{
  public com.leo.skelstub.HelloApp.Hello value = null;

  public HelloHolder ()
  {
  }

  public HelloHolder (com.leo.skelstub.HelloApp.Hello initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.leo.skelstub.HelloApp.HelloHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.leo.skelstub.HelloApp.HelloHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.leo.skelstub.HelloApp.HelloHelper.type ();
  }

}
